{% set package_name = "ads-async" %}
{% set import_name = "ads_async" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  - python >=3.9
  - setuptools_scm
  - pip
  run:
  - python >=3.9

test:
  imports:
  - ads_async
  requires:
  - pytest
  - pytmc

about:
  home: https://github.com/pcdshub/ads-async
  license: SLAC Open License
  summary: Python TwinCAT ADS async tools
